name       : iceauth
version    : 1.0.9
release    : 1
source     :
    - https://xorg.freedesktop.org/archive/individual/app/iceauth-1.0.9.tar.xz : 2cb9dfcb545683af77fb1029bea3fc52dcc8a0666f7b8b2d7373b6ed4c408c05
license    : MIT
component  : xorg.apps
summary    : ICE authority file utility.
description: |
    ICE authority file utility.
builddeps  :
    - pkgconfig(ice)
    - pkgconfig(xorg-macros)
    - xorgproto
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
